name: go-lint
#     ^^^^^^^
# https://github.com/organization/repository/workflows/go-lint/badge.svg
#                                                      ^^^^^^^

on:
  push:
    branches:
      - main
    # NO paths-ignore
  pull_request:
    # NO paths-ignore
  workflow_dispatch:
    inputs: {}

# NOTE: If commit & push continuously, cancel the workflow other than the latest commit.
concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  WORKDIR: .

defaults:
  run:
    shell: bash

jobs:
  paths-ignore:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.paths-ignore.outputs.skip }}
    steps:
      - uses: kunitsucom/github-actions-paths-ignore-alternative@main
        id: paths-ignore
        with:
          paths-ignore: |-
            # substrings of file paths to ignore written in regular expressions
            ^.github/
            ^.*\.md$
            ^.*\.log$
            ^.github/dependabot.yml$
            ^.github/pull_request_template.md$
            ^.github/release.yml$
            ^.github/workflows/label-checker.yml$
            ^.github/workflows/task-list-checker.yml$
            ^CREDITS$
  # > Note: A job that is skipped will report its status as "Success".
  # > It will not prevent a pull request from merging, even if it is a required check.
  # ref. https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#overview
  go-lint:
    runs-on: ubuntu-latest
    needs: paths-ignore
    if: ${{ needs.paths-ignore.outputs.skip != 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: DEBUG
        shell: bash
        run: |
          cat <<'DEBUG_DOC'
          == DEBUG =======================================================
          github.ref: ${{ github.ref }}
          github.event_name: ${{ github.event_name }}
          -- toJSON(github.event.inputs) ---------------------------------
          ${{ toJSON(github.event.inputs) }}
          -- toJSON(github) ----------------------------------------------
          ${{ toJSON(github) }}
          ================================================================
          DEBUG_DOC
      - name: actions/cache for versenv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/versenv
          key: versenv-${{ runner.os }}-${{ hashFiles('**/.versenv.env') }}
          restore-keys: |
            versenv-${{ runner.os }}-
      - name: Add GITHUB_PATH, GITHUB_ENV
        shell: bash
        run: |
          # Update GITHUB_PATH
          cat <<GITHUB_PATH >> $GITHUB_PATH
          ${PWD}/.local/bin
          ${PWD}/${{ env.WORKDIR }}/.local/bin
          ${PWD}/.bin
          GITHUB_PATH
          # Update GITHUB_ENV
          grep -Ev '^\s*$|^\s*#' .versenv.env >> $GITHUB_ENV
      - name: Setup versenv
        shell: bash
        run: |
          # Setup versenv
          direnv allow ${{ env.WORKDIR }}
          make versenv
      - uses: actions/setup-go@v5 # ref. https://github.com/actions/setup-go#usage
        id: setup-go
        with:
          cache: false
          go-version-file: ${{ env.WORKDIR }}/go.mod
      - name: Get Golang info
        id: golang-info
        shell: bash
        run: |
          echo "GOVERSION=$(go version | cut -d' ' -f3)" >> "$GITHUB_OUTPUT"
          echo "GOCACHE=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
      - name: actions/cache for go
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
          # ${{ steps.golang-info.outputs.GOCACHE }}
          key: ${{ runner.os }}-go-${{ steps.golang-info.outputs.GOVERSION }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.golang-info.outputs.GOVERSION }}-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-${{ steps.golang-info.outputs.GOVERSION }}-
            ${{ runner.os }}-go-
      - name: Setup git config for go mod download
        env:
          DEBIAN_FRONTEND: noninteractive
          # GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        working-directory: ${{ env.WORKDIR }}
        shell: bash
        run: |
          set -Eeu -o pipefail -x
          direnv allow .
          if [ -n "${GITHUB_TOKEN-}" ]; then
            direnv exec . bash -Eeux -o pipefail -c 'echo "${GOPRIVATE:-}${GOPRIVATE+,}" | while read -d , -r LINE; do echo "set git config: ${LINE}"; git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@${LINE}".insteadOf "https://${LINE}"; done'
          fi
      - uses: golangci/golangci-lint-action@v5.1.0 # ref. https://github.com/golangci/golangci-lint-action#how-to-use
        with:
          working-directory: ${{ env.WORKDIR }}
          args: --timeout=600s
          version: latest # or v${{ env.GOLANGCI_LINT_VERSION }}
